runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /static
  static_dir: static

- url: /
  script: app.ihelp_handlers.app

- url: /android/post_a_task
  script: app.ihelp_handlers.app

- url: /android/update_profile
  script: app.ihelp_handlers.app

- url: /android/get_all_task
  script: app.ihelp_handlers.app

- url: /android/i_can_help
  script: app.ihelp_handlers.app

- url: /android/i_need_help
  script: app.ihelp_handlers.app

- url: /android/view_task
  script: app.ihelp_handlers.app

- url: /android/change_status
  script: app.ihelp_handlers.app

- url: /android/get_icon
  script: app.ihelp_handlers.app

- url: .*
  script: app.ihelp_handlers.app

# Path variables
- url: /resources
  static_dir: resources

- url: /viewtask
  script: app.view_task.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
