runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /static
  static_dir: static
  
- url: /icanhelp
  script: app.i_can_help.app

- url: /ineedhelp
  script: app.i_need_help.app

- url: /viewtask
  script: app.view_task.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
